# Generated by Django 5.0.3 on 2024-10-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
