# Generated by Django 5.0.3 on 2024-10-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='nivel',
            new_name='periodo',
        ),
    ]
