# Generated by Django 5.0.3 on 2024-10-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_alter_curso_codigo_alter_estudante_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_campus', models.CharField(max_length=4)),
                ('numero_do_campus', models.IntegerField(choices=[('1', 'Campus 1'), ('2', 'Campus 2'), ('3', 'Campus 3'), ('4', 'Campus 4'), ('5', 'Campus 5'), ('6', 'Campus 6'), ('7', 'Campus 7'), ('8', 'Campus 8')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.AlterField(
            model_name='estudante',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
