# Generated by Django 5.0.3 on 2024-10-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_campus_professor_alter_estudante_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_do_predio', models.IntegerField(default='1', max_length=3)),
                ('status_predio', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_da_sala', models.IntegerField(default='1', max_length=4)),
                ('status_sala', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='campus',
            name='codigo_campus',
        ),
        migrations.AddField(
            model_name='campus',
            name='status_campus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='numero_do_campus',
            field=models.IntegerField(default='1', max_length=2),
        ),
    ]
