# Generated by Django 5.0.3 on 2024-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_predio_sala_remove_campus_codigo_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='numero_do_campus',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='numero_do_predio',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero_da_sala',
            field=models.IntegerField(default='1'),
        ),
    ]
