# Generated by Django 5.0.3 on 2024-10-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_alter_campus_numero_do_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='limite_de_predios',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='predio',
            name='limite_de_salas',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='sala',
            name='limite_de_alunos',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='campus',
            name='numero_do_campus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='predio',
            name='numero_do_predio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero_da_sala',
            field=models.IntegerField(default=1),
        ),
    ]
