# Generated by Django 5.0.3 on 2024-10-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0009_campus_limite_de_predios_predio_limite_de_salas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='status_campus',
            field=models.CharField(choices=[('L', 'LIBERADO PARA USO'), ('N', 'NÃO PODE SER USADO')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='predio',
            name='status_predio',
            field=models.CharField(choices=[('L', 'LIBERADO PARA USO'), ('N', 'NÃO PODE SER USADO')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='sala',
            name='status_sala',
            field=models.CharField(choices=[('L', 'LIBERADO PARA USO'), ('N', 'NÃO PODE SER USADO')], default='L', max_length=1),
        ),
    ]
